# Generated by Django 5.1.3 on 2024-12-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_deliveries", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app_products.productsmodel",
                verbose_name="Product",
            ),
        ),
    ]
