# Generated by Django 5.1.3 on 2024-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_deliveries", "0002_alter_orderitemmodel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending_for_courier", "Pending for a Courier"),
                    ("pending_for_restaurant", "Pending for a Restaurant"),
                    ("confirmed_by_restaurant", "Confirmed by a Restaurant"),
                    ("delivering", "Delivering"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending_for_courier",
                max_length=25,
                verbose_name="Order Status",
            ),
        ),
    ]
