# Generated by Django 5.1.3 on 2024-12-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_deliveries", "0003_alter_ordermodel_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitemmodel",
            name="price_per_item",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitemmodel",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
