# Generated by Django 5.1.3 on 2024-12-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_deliveries", "0004_alter_orderitemmodel_price_per_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordermodel",
            options={},
        ),
    ]
