# Generated by Django 5.1.3 on 2024-12-10 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_branch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchmodel",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="branchmodel",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="branchmodel",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="branchmodel",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="branchmodel",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
