# Generated by Django 5.1.3 on 2024-12-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_branch", "0002_remove_branchmodel_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchProductsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="app_branch.branchmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Product",
                "verbose_name_plural": "Branch Products",
            },
        ),
    ]
