# Generated by Django 5.1.3 on 2024-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_users",
            "0004_alter_usermodel_first_name_alter_usermodel_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("restaurant", "Restaurant"),
                    ("branch", "Branch"),
                    ("courier", "Courier"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
