# Generated by Django 5.1.3 on 2024-12-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_company", "0002_remove_restaurantmodel_manager_and_more"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantProductsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="app_products.productsmodel",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="app_company.restaurantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant Product",
                "verbose_name_plural": "Restaurant Products",
                "unique_together": {("restaurant", "product")},
            },
        ),
    ]
